### ISSUE TITLE
review 'rate' phenotyes

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-phenotype-ontology#148]
Make sure 'rate' is in label and that definition is clear about different possible meanings of rate

**Comment by Clare72** [comment]
Given the current 'accelerated'/'slower' definitions of the premature/delayed aging phenotypes, these seem like they would be better suited to RateOfContinuousProcess patterns (for speed of a continuous process, rather than frequency or proportion of time of a process that may stop and start).
Labels should probably also be something like 'increased aging speed' and 'decreased aging speed'.

What do you think @arzuozturk @vmt25 ?

**Comment by Clare72** [comment]
also, are you happy with labels of 'hyperactive' and 'hypoactive'? Or should these be 'increased/decreased rate of movement'?

**Comment by arzuozturk** [comment]
_Given the current 'accelerated'/'slower' definitions of the premature/delayed aging phenotypes, these seem like they would be better suited to RateOfContinuousProcess patterns (for speed of a continuous process, rather than frequency or proportion of time of a process that may stop and start).
Labels should probably also be something like 'increased aging speed' and 'decreased aging speed'.

What do you think @arzuozturk @vmt25 ?_

Sounds reasonable to me.

_also, are you happy with labels of 'hyperactive' and 'hypoactive'? Or should these be 'increased/decreased rate of movement'?_

As long as their definitions are the same, I don't mind the names. If changing them to 'increased/decreased rate of movement' makes sense ontologically please go ahead and do it.

Thanks.
Arzu
