### ISSUE TITLE
Remove object property details from fbdv_extension

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-phenotype-ontology#150]
these all seem to be in the RO import - so not needed here.

**Comment by Clare72** [comment]
The fbdv_extension component seems to add a bunch of immediately_preceded_by relationships to FBdv terms. Is there a reason that these can't just be moved to FBdv? @dosumis

**Comment by dosumis** [comment]
I assume this is to ensure that the lethal phase EC defs work.  No longer recall why they are here rather than FBdv.  Might have been something to do with FlyBase expectations for FBdv and some scripts used by Harvard to calc intermediate stages in prod.  Not sure any of this is still relevant.  If Harvard are still doing this - you may want to look into how.  We have much better alternatives to replace and creaky PERL scripts written for this job.

**Comment by Clare72** [comment]
I can always put them into FBdv, but strip them out of the FlyBase version. I think that would make more sense than having them here.
