### ISSUE TITLE
dpoAbnormalBiologicalProcessByQuality needs to be assigned to uPheno patterns

### ISSUE THREAD

**Issue by matentzn** [FlyBase/drosophila-phenotype-ontology#29]
I have started going through your tsv files; the next goal is to break out the individual phenotypes and assign them to the correct uPheno patterns.

https://github.com/FlyBase/drosophila-phenotype-ontology/blob/master/src/patterns/data/original/dpoAbnormalBiologicalProcessByQuality.tsv

For example:
```
http://purl.obolibrary.org/obo/FBcv_0000718	decreased cell growth	http://purl.obolibrary.org/obo/GO_0016049	cell growth	http://purl.obolibrary.org/obo/PATO_0000911	decreased rate
```

Needs to be placed in a tsv corresponding to the [abnormallyDecreasedRateOfBiologicalProcess](https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormallyDecreasedRateOfBiologicalProcess.yaml) pattern.

After the tsv is created and the respective phenotypes are placed in there, you need to:
1) delete the rows from the dpoAbnormalBiologicalProcessByQuality tsv (the ones you moved over)
2) delete the last two columns of the abnormallyDecreasedRateOfBiologicalProcess.tsv (the quality and its label; these are now covered by the pattern).

Note that this work may involve creating new uPheno patterns! Ping me of you need help for that.

**Comment by Clare72** [comment]
hyper/hypoactive - currently using increased/decreased frequency, but rate may be more appropriate.

chemical resistant/sensitive - might be best to use [abnormallyIncreasedResistanceToChemicalEntity](https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-workshop/abnormallyIncreasedResistanceToChemicalEntity.yaml) (and 'Decreased' version). I think this fits the text def better, but as before, the fact that it should only be 'toxic effects' would not be captured in the logical definition.

radiation resistant/sensitive - there does not currently seem to be an appropriate pattern. PATO has [sensitivity to irradiation](http://purl.obolibrary.org/obo/PATO_0001806) terms, so perhaps we should use these rather than patternising current logical def. As with 'chemical' terms, the requirement for effects to be 'toxic' would still not be reflected in the logical definition.

increased/decreased occurence of cell division - looks like we need new patterns for increased/decreased occurence of a process (this is a bit different to rate).
