### ISSUE TITLE
Consider revising definitions (4)

### ISSUE THREAD

**Issue by matentzn** [FlyBase/drosophila-phenotype-ontology#7]
The following 4 definitions contain disjunctions (OR statements), which will obstruct their classification in a multispecies context. It also seems that this makes them unnecessarily complex; 

- ['cell death defective'](https://www.ebi.ac.uk/ols/ontologies/fbcv/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBcv_0000424): Here I would consider reducing to GO:cell death, rather than regulation of cell death?

EDIT:
The three behaviours where now changed to the 'inheres in part of' pattern.
- ['courtship behavior defective'](https://www.ebi.ac.uk/ols/ontologies/fbcv/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBcv_0000399): should probably simply be inheres in courtship behaviour: https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormalBehavior.yaml
- ['mating behavior defective'](https://www.ebi.ac.uk/ols/ontologies/fbcv/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBcv_0000721): Same as above
- ['mating defective'](https://www.ebi.ac.uk/ols/ontologies/fbcv/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBcv_0000400): Same as above

**Comment by matentzn** [comment]
Maybe best wait with this change until https://github.com/FlyBase/drosophila-phenotype-ontology/pull/5 is merged, @Clare72

**Comment by Clare72** [comment]
'cell death defective': I think removing GO 'regulation of cell death' better matches the text definition - the cause (e.g. regulation) does not matter. However, if we made a phenotype for 'regulation of cell death defective', this would then not be a 'cell death defective' phenotype because GO 'regulation of cell death' does not (and should not) have an is_a relationship to GO 'cell death'. Personally, I think this would be fine as defective regulation may not necessarily result in actual changes to the number of cells dying (which is the phenotype here).

'courtship behavior defective': In GO, 'male courtship behavior' is not a 'courtship behavior', but a 'mating behavior' that is part_of some 'courtship behavior'. Looks like this happened due to this ticket: https://github.com/geneontology/go-ontology/issues/4165, but it is not clear why part_of rather than is_a. We need 'courtship behavior defective' to also cover gender-specific behaviors, so I think this needs fixing in the GO. Current logical def for 'courtship behavior defective' looks like a workaround for this problem.

'mating behavior defective': Looks like this should be fine as everything in GO (including 'male courtship behavior') is linked up by is_a relationships (although tree structure is not perfect).

'mating defective': Changing this would mean that 'mating behavior defective' is no longer an is_a child, which is probably fine. I don't think a small change in pulse song frequency or wing extension angle should infer 'mating defective' as males might otherwise mate normally, but others may disagree. This is similar to part_of issues discussed on the calls i.e. should an abnormal component of a thing mean an abnormal thing.

@dosumis - looks like you made all four of the terms in question, do you have anything to add?

**Comment by matentzn** [comment]
Noticed these inferences were lost in new simple release:

```
+ SubClassOf(<http://purl.obolibrary.org/obo/FBcv_0000399> <http://purl.obolibrary.org/obo/FBcv_0000721>)
+ SubClassOf(<http://purl.obolibrary.org/obo/FBcv_0000721> <http://purl.obolibrary.org/obo/FBcv_0000387>)
+ SubClassOf(<http://purl.obolibrary.org/obo/FBcv_0000721> <http://purl.obolibrary.org/obo/FBcv_0000400>)
```

**Comment by matentzn** [comment]
These ones were added in the new dpo-simple release:

```
- SubClassOf(<http://purl.obolibrary.org/obo/FBcv_0000399> <http://purl.obolibrary.org/obo/FBcv_0001347>)
- SubClassOf(<http://purl.obolibrary.org/obo/FBcv_0000401> <http://purl.obolibrary.org/obo/FBcv_0000400>)
- SubClassOf(<http://purl.obolibrary.org/obo/FBcv_0000402> <http://purl.obolibrary.org/obo/FBcv_0000387>)
- SubClassOf(<http://purl.obolibrary.org/obo/FBcv_0000402> <http://purl.obolibrary.org/obo/FBcv_0000400>)
- SubClassOf(<http://purl.obolibrary.org/obo/FBcv_0000402> <http://purl.obolibrary.org/obo/FBcv_0000721>)
- SubClassOf(<http://purl.obolibrary.org/obo/FBcv_0000721> <http://purl.obolibrary.org/obo/FBcv_0001347>)
```

@Clare72 I think this is all due to what you discovered here, but if you want, you can verify whether this is ok for now.

**Comment by Clare72** [comment]
Translation:
>SubClassOf(<http://purl.obolibrary.org/obo/FBcv_0000399> <http://purl.obolibrary.org/obo/FBcv_0000721>) [removed]
SubClassOf(<http://purl.obolibrary.org/obo/FBcv_0000399> <http://purl.obolibrary.org/obo/FBcv_0001347>) [added]

'courtship behavior defective' falls under 'phenotype' rather than 'mating behavior defective'

>SubClassOf(<http://purl.obolibrary.org/obo/FBcv_0000721> <http://purl.obolibrary.org/obo/FBcv_0000387>) [removed]
SubClassOf(<http://purl.obolibrary.org/obo/FBcv_0000721> <http://purl.obolibrary.org/obo/FBcv_0000400>) [removed]
SubClassOf(<http://purl.obolibrary.org/obo/FBcv_0000721> <http://purl.obolibrary.org/obo/FBcv_0001347>) [added]

'mating behavior defective' falls under 'phenotype' rather than 'behavior defective' and 'mating defective'

>SubClassOf(<http://purl.obolibrary.org/obo/FBcv_0000401> <http://purl.obolibrary.org/obo/FBcv_0000400>) [added]

'mating rhythm defective' additionally falls under 'mating defective'

>SubClassOf(<http://purl.obolibrary.org/obo/FBcv_0000402> <http://purl.obolibrary.org/obo/FBcv_0000387>) [added]
SubClassOf(<http://purl.obolibrary.org/obo/FBcv_0000402> <http://purl.obolibrary.org/obo/FBcv_0000400>) [added]
SubClassOf(<http://purl.obolibrary.org/obo/FBcv_0000402> <http://purl.obolibrary.org/obo/FBcv_0000721>) [added]

'song defective' additionally falls under 'behavior defective', 'mating defective' 'mating behavior defective'

**Comment by Clare72** [comment]
I also see these 'changes' in the old edit file when reasoned with ELK, reasoning with hermit fixes it. The new edit file is taking a ridiculously long time to reason with hermit, but I suspect that it will solve the problem.

**Comment by matentzn** [comment]
If course!!! I am so dense! That’s why I wanted these patterns changed in the first place. Elk does not do OR! I will try to convince David today and that’s it. All else later.

**Comment by matentzn** [comment]
The last subclass axiom missing is this one:

```
SubClassOf(<http://purl.obolibrary.org/obo/FBcv_0000721> <http://purl.obolibrary.org/obo/FBcv_0000387>)
```

**Comment by Clare72** [comment]
All now moved to patterns - closing
